---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: document
  path: about
  label: About Us
- type: directory
  path: contact/**/*
  label: Contact us
  create: all
  match: "**/*"
- type: directory
  path: ''
  label: Home
  create: all
  match: "**/*"
- type: directory
  path: ''
  label: Journal
  create: all
  match: "**/*"
  templates:
  - section
- type: directory
  path: projects
  label: Projects
  create: documents
  match: "**/*.md"
  templates:
  - project
- type: directory
  path: about
  label: About
  create: documents
  match: "**/*.md"
  templates:
  - journal
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
